version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: wp-nginx
    ports:
      - "8090:80"
      - "8443:443"
    expose:
      - "8443"  # To otwiera port 8443 wewnątrz sieci kontenerów
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - php
    networks:
      wp-network:
        aliases:
          - localhost  # To mówi: "W tej sieci ja (Nginx) odpowiadam też na nazwę localhost"

  php:
      build:
        context: .
        dockerfile: dockerfile-php
      container_name: wp-php
      extra_hosts:
        - "localhost:host-gateway" # To musi zostać
      networks:
        wp-network:
          aliases:
            - php-container # Opcjonalnie, dla porządku
      volumes:
        - ./src:/var/www/html

  db:
    image: mysql:8
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - wp-network

  node:
    image: node:18
    container_name: wp-node
    working_dir: /app
    volumes:
      - ./src:/app
    command: tail -f /dev/null
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
